### ISSUE TITLE
'SSN_to_SSN2' is deprecated?

### ISSUE THREAD

**Issue by KGBrennan** [USEPA/SSN2#19]
Hi, is SSN_to_SSN2() depreciated? if so, why and will this cause problems going from SSN to SSN2 objects? 

ssn2 <- SSN_to_SSN2(ssn)
Warning message:
'SSN_to_SSN2' is deprecated.
Use 'ssn_import' instead.
See help("Deprecated")

**Comment by michaeldumelle** [comment]
Hi @KGBrennan and so sorry for the late response here! This issue got mixed up with some other issues that were part of a journal article review for the software.

`SSN_to_SSN2()` is [deprecated](https://lifecycle.r-lib.org/articles/stages.html), but it is still available and will be available for some time. The main purpose of the function is to provide support for people that have original `SSN` objects in their saved workspaces and want a quick way to make them compatible with `SSN2`. Because `SSN` is archived, we encourage users to eventually use `SSN2::ssn_import()` to import their `SSN` objects directly from `.ssn` folders on their machines.
